apiVersion: v1
kind: Service
metadata:
  name: art-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 195.58.54.98
spec:
  type: LoadBalancer

#kind: Service
#apiVersion: v1
#metadata:
#  name: art-service
#spec:
#  selector:
#    pod: art-container
#  ports:
#  - protocol: TCP
#    port: 80
#  type: ClusterIP